[project]
authors = ["notPlancha <andre.plancha@hotmail.com>"]
channels = ["conda-forge"]
name = "eda"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
ipynb_to_py = "jupyter nbconvert --to python"

[dependencies]
python = ">=3.13.2,<3.14"
numpy = ">=2.2.3,<3"
pandas = ">=2.2.3,<3"
jupyter = ">=1.1.1,<2"
scikit-learn = ">=1.6.1,<2"
seaborn = ">=0.13.2,<0.14"
plotnine = ">=0.14.5,<0.15"
patchworklib = ">=0.6.3,<0.7" # doesnt work
plotly = ">=6.0.0,<7"
typst = ">=0.13.1,<0.14"

[pypi-dependencies]
pyedakit = ">=0.1.4, <0.2"
scikit-misc = ">=0.5.1, <0.6"
